### ISSUE TITLE
How do i modify the hostname and port?

### ISSUE THREAD

**Issue by CosmicStar98** [floatzeI/2016-roblox#21]
title says it all. i need to change this because i'm trying to host this on my vps but cant find a config anywhere to tweak such a thing.

thanks in advance!

**Comment by floatzeI** [comment]
Apparently the recommended way is to either set the "PORT" environmental variable, or run `next dev -p 1000` or `next start -p 1000` (replacing `1000` with the port you want to use). More info is available here: [stackoverflow.com/questions/60147499/how-to-set-port-in-next-js](https://stackoverflow.com/questions/60147499/how-to-set-port-in-next-js)
