### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jhhuik** [floatzeI/2016-roblox#34]
i got a syntax or whatever its called error,      

git clone git@github.com:floatzeI/2016-roblox.git
^^^^^^

theres git clone in it

cd 2016-roblox
    ^^^^

theres numbers in it so i get another error

**Comment by floatzeI** [comment]
You'll have to install git to run git commands (such as git clone). https://git-scm.com/download/win

**Comment by jhhuik** [comment]
thx

**Comment by jhhuik** [comment]
i literally have no idea what componets i should use but closed.

**Comment by jhhuik** [comment]
bruh i also have no idea what should be gits default editor

**Comment by floatzeI** [comment]
I don't use windows so I cannot help with the git installation. There are many videos online about how to install git, such as this one: https://www.youtube.com/watch?v=4xqVv2lTo40

**Comment by jhhuik** [comment]
now i got This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by jhhuik** [comment]
oops windows defender moment

**Comment by jhhuik** [comment]
bruh i closed command prompt and it broke

**Comment by jhhuik** [comment]
yes it works but i have a question


should i keep command prompt open

**Comment by jhhuik** [comment]
every time i close it i get a localhost error
