### ISSUE TITLE
Replace "/thumbs/asset.ashx" with thumbnail endpoints

### ISSUE THREAD

**Issue by floatzeI** [floatzeI/2016-roblox#7]
All the /thumbs/*.ashx redirect URLs were supposed to be removed ages ago, but luckily that hasn't happened yet (although that probably means it could happen any minute now!). If images ever stop loading one day, this is probably why.

**Comment by Rxplicat3dStxr4ge** [comment]
looks like "/thumbs/asset.ashx" got removed, images refused to load

**Comment by floatzeI** [comment]
This is fixed now
